# Generated by Django 3.0.7 on 2020-07-27 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='executemodel',
            name='caller',
            field=models.CharField(default='caller', max_length=255),
        ),
    ]
