# Generated by Django 3.0.7 on 2020-07-28 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0002_executemodel_caller'),
    ]

    operations = [
        migrations.AddField(
            model_name='executemodel',
            name='stop',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='executemodel',
            name='finish',
            field=models.BooleanField(default=False),
        ),
    ]
