# Generated by Django 3.0.7 on 2020-07-28 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0004_auto_20200728_1424'),
    ]

    operations = [
        migrations.RenameField(
            model_name='executemodel',
            old_name='stop',
            new_name='skip',
        ),
    ]
